# Generated by Django 4.0.3 on 2022-03-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('dataset_url', models.TextField(blank=True, db_column='dataset_url', null=True)),
                ('isrefreshable', models.BooleanField(blank=True, db_column='isRefreshable', null=True)),
                ('isonpremgatewayrequired', models.BooleanField(blank=True, db_column='isOnPremGatewayRequired', null=True)),
            ],
            options={
                'db_table': 'datasets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datasources',
            fields=[
                ('dataset_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(max_length=50)),
                ('datasource_name', models.CharField(blank=True, max_length=50, null=True)),
                ('datasource_id', models.CharField(max_length=255)),
                ('gateway_id', models.CharField(max_length=255)),
                ('gateway_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gateway_status', models.CharField(blank=True, max_length=25, null=True)),
                ('conection_type', models.CharField(blank=True, max_length=25, null=True)),
                ('cred_type', models.CharField(blank=True, max_length=25, null=True)),
                ('inserted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'datasources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gateways',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=50)),
                ('datasource_name', models.CharField(blank=True, max_length=50, null=True)),
                ('datasource_id', models.CharField(max_length=255)),
                ('gateway_id', models.CharField(max_length=255)),
                ('gateway_name', models.CharField(blank=True, max_length=50, null=True)),
                ('datasource_status', models.CharField(max_length=12)),
                ('inserted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'gateways',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefreshHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=50)),
                ('dataset_id', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('refresh_type', models.CharField(max_length=25)),
                ('request_id', models.CharField(max_length=255)),
                ('history_id', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('total_time', models.TimeField()),
                ('inserted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'refresh_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduledRefresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=50)),
                ('dataset_id', models.CharField(max_length=255)),
                ('ativo', models.BooleanField()),
                ('atualizacao', models.TimeField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'scheduled_refresh',
                'managed': False,
            },
        ),
    ]
